### ISSUE TITLE
Infinite Loop on Finalising Quiz

### ISSUE THREAD

**Issue by adamsfallen** [HungryTurtleCode/TurtleFactQuiz#1]
If a user selects answers using the top buttons as navigation (versus the Continue button), it doesn't calculate numQuestionsAnswered correctly. As a result, after you select answers for all questions, the app gets stuck in an infinite loop where it iterates through the while(!breakOut) loop but can't find an unselected question.

One fix is to change the way numQuestionsAnswered is calculated when the user clicks "Continue" ala...

`numQuestionsAnswered = 0;
                for(var i = 0; i < quizLength; i++){
                        if(DataService.quizQuestions[i].selected !== null){
                        numQuestionsAnswered++;
                        }
                }`

**Comment by adiman9** [comment]
You are spot on! Thanks for pointing this out. I will add and commit your changes asap. I will also create another video on the end of the course to point out this bug.

Thanks again

**Comment by adiman9** [comment]
I have fixed this bug in the code. I am now closing this issue. Thanks
